enterNamePlayer = False         # enter the name of the player
animationOn = True              # movement animation
speedAnimation = 512            # speed of the animation
fps = 30                        # fps
antialias = 1                   # font antialias
debug = True
window_width = 900
window_height = 640
window_title = "G4"
fullscreen = False
